import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";

const Play = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;

  a {
    width: 300px;
    height: 300px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: 800;
    font-size: 2rem;
    color: var(--amber-300);
    background-color: var(--amber-600);
    box-shadow: inset -80px -80px 80px -20px #b2185a;
    -webkit-box-shadow: inset -80px -80px 80px -20px #b2185a;
    border-radius: 100%;

    &:hover {
      color: var(--white);
      background-color: var(--sky-300);
      box-shadow: inset -80px -80px 80px -20px var(--indigo-600);
      -webkit-box-shadow: inset -80px -80px 80px -20px var(--indigo-600);
    }

    animation: a 2.5s ease infinite;
    @keyframes a {
      0% {
        transform: translateY(-5px);
        letter-spacing: 0px;
      }

      25% {
        letter-spacing: 3px;
      }

      50% {
        transform: translateY(5px);
        letter-spacing: 0px;
      }

      75% {
        letter-spacing: 3px;
      }

      100% {
        transform: translateY(-5px);
        letter-spacing: 0px;
      }
    }

    @media screen and (min-width: 480px) {
      width: 400px;
      height: 400px;
      font-size: 3rem;
    }
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>MathMess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/mathmess.png" />
      </Head>
      <Play>
        <Link href={"/games"}>¡JUGUEMOS!</Link>
      </Play>
    </>
  );
}
